// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzxapbisjfinjnxyhkyi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6eGFwYmlzamZpbmpueHloa3lpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjg0NzYsImV4cCI6MjA2NTc0NDQ3Nn0.ypDcv6o4AZpMv5nn60fFdl2W1NMGESuadzJ-n6_KP0o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);